input:
  type: gibberish
  plugin:
    length: 10

pipeline:
  processors:
  - encode:
      scheme: base64
  - bloblang: 'root.gibberish = content().string()'
  - throttle:
      period: 1s

output:
  type: blue_stdout
